### ISSUE TITLE
Detail page not working on aiida-v2

### ISSUE THREAD

**Issue by eimrek** [lsmo-epfl/discover-curated-cofs#31]
Currently, materials cloud is running on the aiida-v2 branch.

The "details page" is not opening:

https://www.materialscloud.org/discover/curated-cofs#mcloudHeader

Could be related to https://github.com/materialscloud-org/aiida-explorer/issues/39

**Comment by ltalirz** [comment]
The logs of the docker container will typically provide some insight

**Comment by eimrek** [comment]
Here's the error from `docker logs`:

```
2022-07-20 12:00:23,210 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f9ea9cfa520>: SVG pane does not support objects of type 'Digraph'.
File "base.py", line 117, in _type_error:
raise ValueError("%s pane does not support objects of type '%s'." % Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/app/detail/main.py", line 96, in <module>
    ("Workflow's graph", explorer.graph()),
  File "/app/detail/main.py", line 55, in graph
    column = pn.Column(pn.pane.SVG(get_graph(self.mat_dict)))
  File "/usr/local/lib/python3.8/site-packages/panel/pane/base.py", line 108, in __init__
    self._type_error(object)
  File "/usr/local/lib/python3.8/site-packages/panel/pane/image.py", line 200, in _type_error
    super(SVG, self)._type_error(object)
  File "/usr/local/lib/python3.8/site-packages/panel/pane/image.py", line 69, in _type_error
    super(ImageBase, self)._type_error(object)
  File "/usr/local/lib/python3.8/site-packages/panel/pane/base.py", line 117, in _type_error
    raise ValueError("%s pane does not support objects of type '%s'." %
ValueError: SVG pane does not support objects of type 'Digraph'.
```

Doesn't seem to be related to my aiida-v2 commit (https://github.com/materialscloud-org/discover-curated-cofs/commit/01d45c1096e8ba4a9da3e40e0a456fae3dc3f69b). Except perhaps the python version going from 3.7 to 3.8.

I tried installing exactly the same versions of `bokeh`, `panel` and `graphviz`, as in the old server (where this was working), but this didn't help.

Any ideas what could have caused this?
